=== BackupTheBerlios/ghns-svn/trunk/spec/data/ghnsdownload.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT ghnsdownload (stuff*)>
<!ELEMENT stuff (name*,author,licence,summary*,version,release,releasedate,
                 preview*,payload*,rating?,downloads?)>
  <!ATTLIST stuff type CDATA #IMPLIED>

<!ELEMENT name (#PCDATA)>
  <!ATTLIST name lang CDATA #IMPLIED>

<!ELEMENT author (#PCDATA)>
  <!ATTLIST author email CDATA #REQUIRED>

<!ELEMENT licence (#PCDATA)>
  <!ATTLIST licence agreement (gpl | publicdomain | custom) #REQUIRED>
  <!ATTLIST licence conditions CDATA #IMPLIED>

<!ELEMENT summary (#PCDATA)>
  <!ATTLIST summary lang CDATA #REQUIRED>

<!ELEMENT version (#PCDATA)>

<!ELEMENT release (#PCDATA)>

<!ELEMENT releasedate (#PCDATA)>

<!ELEMENT url (#PCDATA)>

<!ELEMENT preview (#PCDATA)>
  <!ATTLIST preview lang CDATA #REQUIRED>

<!ELEMENT payload (#PCDATA)>
  <!ATTLIST payload lang CDATA #REQUIRED>

<!ELEMENT rating (#PCDATA)>

<!ELEMENT downloads (#PCDATA)>

=== BackupTheBerlios/ghns-svn/trunk/spec/data/stuff.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ghnsdownload SYSTEM "ghnsdownload.dtd">
<ghnsdownload>
  <stuff type="app/media">
    <name lang="en">Some Name</name>
    <author email="some_guy@some.mail.server">Anonymous Guy</author>
    <licence agreement="gpl">LicenceKey</licence>
    <summary lang="en">This is what it is all about.</summary>
    <version>1.0</version>
    <release>1</release>
    <releasedate>2005-06-17</releasedate>
    <preview lang="en">http://some.http.server/preview.png</preview>
    <payload lang="en">http://some.http.server/coolstuff.tar.gz</payload>
    <rating>10</rating>
    <downloads>0</downloads>
  </stuff>
</ghnsdownload>
